### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by BoobalanRP**

### CODE REVIEW

**Comment by BoobalanRP** [comment]
Created a new issue [The password format is not given #2](https://github.com/fssa-batch3/boobalan.ravichandran__web_project/issues/2) in GitHub

**Comment by santhosh2808** [comment]
Created a new issue [mobile number input  #3](https://github.com/fssa-batch3/boobalan.ravichandran__web_project/issues/3) in GitHub

**Comment by santhosh2808** [comment]
Created a new issue [contact information mobile and mail input #4](https://github.com/fssa-batch3/boobalan.ravichandran__web_project/issues/4) in GitHub

**Comment by santhosh2808** [comment]
Created a new issue [mobile number input #5](https://github.com/fssa-batch3/boobalan.ravichandran__web_project/issues/5) in GitHub

**Comment by santhosh2808** [comment]
Created a new issue [date of birth not show #6](https://github.com/fssa-batch3/boobalan.ravichandran__web_project/issues/6) in GitHub

**Comment by santhosh2808** [comment]
Created a new issue [log out not hided #7](https://github.com/fssa-batch3/boobalan.ravichandran__web_project/issues/7) in GitHub

**Pull request closed without merging**
